export const FETCH_EMPLOYEE_LIST_START = 'FETCH_EMPLOYEE_LIST_START';
export const FETCH_EMPLOYEE_LIST_SUCCESS = 'FETCH_EMPLOYEE_LIST_SUCCESS';
export const FETCH_EMPLOYEE_LIST_ERROR = 'FETCH_EMPLOYEE_LIST_ERROR';

export const RESET_STATE_EMPLOYEE_LIST = 'RESET_STATE_EMPLOYEE_LIST';