export const GET_EMPLOYEE_DETAIL_START = 'GET_EMPLOYEE_DETAIL_START';
export const GET_EMPLOYEE_DETAIL_SUCCESS = 'GET_EMPLOYEE_DETAIL_SUCCESS';
export const GET_EMPLOYEE_DETAIL_ERROR = 'GET_EMPLOYEE_DETAIL_ERROR';

export const UPDATE_EMPLOYEE_START = 'UPDATE_EMPLOYEE_START';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_ERROR = 'UPDATE_EMPLOYEE_ERROR';

export const RESET_STATE_EMPLOYEE_EDIT = 'RESET_STATE_EMPLOYEE_EDIT';